### ISSUE TITLE
Enemies should start in their original state upon player respawn from checkpoint

### ISSUE THREAD

**Issue by fatjosephina** [mcdonaldduncan/Freebooter#152]
Enemies should start in their original position, activation, state, health, etc. when the player respawns.

**Comment by mcdonaldduncan** [comment]
Hey Joseph, can you please provide some context? Which enemies are not resetting? They are all resetting fine during my testing

**Comment by mcdonaldduncan** [comment]
Also, please give issues a status on the dev board when you create them. Moved to backlog for now

**Comment by mcdonaldduncan** [comment]
Just an update because none got added here by author, this is not a bug or really even something unexpected. A designer made a feature that is not supported by the checkpoint system and calls it a bug when things dont work.
