### ISSUE TITLE
Cut wallrunning

### ISSUE THREAD

**Issue by Sebp23** [mcdonaldduncan/Freebooter#196]
Wallrunning should no longer be in the game

**Comment by GavinKWade01** [comment]
Overgrowth level has been updated with removed wallrunning.

**Comment by fatjosephina** [comment]
Charon 13 has been updated as well.

**Comment by Sebp23** [comment]
Behavior has been removed from the inspector and commented out in FirstPersonController.cs


https://user-images.githubusercontent.com/57201896/222199727-00db5221-dd12-4340-a8e5-a9e14ccb6188.mp4
