### ISSUE TITLE
Art and Design: Props

### ISSUE THREAD

**Issue by KCarre** [mcdonaldduncan/Freebooter#203]

**Comment by KCarre** [comment]
Charon

**Comment by KCarre** [comment]
Overgrowth

**Comment by KCarre** [comment]
**Venice**

- [ ] Single Barrel
- [ ] Group of Barrels with Fishnet cast over it
- [ ] Wodden Fruit Crate
- [ ] Wooden Shipping Crate
- [ ] Single Book
- [ ] Stack of Books
- [ ]  Normal Bookshelf
- [ ] Broken Bookshelf
- [ ] Evacuation Poster
- [ ] Wanted Poster For Level Boss
- [ ] Lamp That Can Attatch To Building (1 Lantern)
- [ ] Wellies (Rain Boots)
- [ ] String of Lightbulbs
- [ ] Venice Streetlamp (3 Lanterns)

**Comment by GavinKWade01** [comment]
The cargo crane is no longer needed in Overgrowth, I removed that from the checklist.
