### ISSUE TITLE
Fix Issues while scrolling with only shotgun in inventory

### ISSUE THREAD

**Issue by mcdonaldduncan** [mcdonaldduncan/Freebooter#223]
errors when attempting to switch weapons while only having the shotgun

![Image](https://user-images.githubusercontent.com/72177724/225164537-fcaebd34-5c02-4663-8afa-08c7281637e4.png)

**Comment by Sebp23** [comment]
Not able to reproduce this error in any of the levels. Do you have more specific reproduction steps?

**Comment by mcdonaldduncan** [comment]
@Sebp23 it happens on all of the levels, if it is not happening for you check to see if you have changes that have not been pushed

**Comment by mcdonaldduncan** [comment]
As far as replication, I go to any of the levels and scroll up on the mousewheel

**Comment by Sebp23** [comment]
Ok so it happens only if you scroll up first. I'll look into it, should be a quick fix.

**Comment by Sebp23** [comment]
Fixed in commit
